### ISSUE TITLE
V7.0.5 installs fine, but upgrade to V8.0.0 fails

### ISSUE THREAD

**Issue by GerardTromp** [aadler/Delaporte#2]
Greetings!

I just proceeded to try to upgrade from version version 7.0.5 which was installed less than a month ago when I upgraded R to version 4.0.3. Version 7.0.5 installed fine with no errors. The upgrade fails as follows:

```
R CMD INSTALL Delaporte_8.0.0.tar.gz
* installing to library \u2018/opt/bioinfo/lib64/R/library\u2019
* installing *source* package \u2018Delaporte\u2019 ...
** package \u2018Delaporte\u2019 successfully unpacked and MD5 sums checked
** using staged installation
** libs
gfortran -m64 -fopenmp  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c  utils.f95 -o utils.o
gfortran -m64 -fopenmp  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c  lgamma.f95 -o lgamma.o
gfortran -m64 -fopenmp  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c  delaporte.f95 -o delaporte.o
delaporte.f95:87.10:

    !$omp declare simd(ddelap_f_s) uniform(alpha, beta, lambda) inbranch
          1
Error: Unclassifiable OpenMP directive at (1)
delaporte.f95:88.10:

    !$omp declare simd(ddelap_f_s) uniform(alpha, beta, lambda) notinbranch
          1
Error: Unclassifiable OpenMP directive at (1)
delaporte.f95:105.22:

```

It would seem that it is dependent on a new(er) version of openmp (either system package or R package, or both). 

It might be useful for the install script to verify the prerequisites.

**Comment by aadler** [comment]
Hello, @GerardTromp.

Yes, CRAN let me know last week that some of the compilers in use are not OpenMP 4.5 compliant and that SIMD declarations would not work. I will be pushing 8.0.1 to CRAN this week which removes the SIMD calls and just uses the OpenMP 3.x compliant parallel do loops. That should install without a problem. Once 8.0.1 is released, please respond back here if it was successful or not. My apologies for the inconvenience.
